create Header and Footer Component
peaksoft-school/gadgetarium-js9 pull request #13
Opened 2023-07-09 17:52 UTC by Tugolbay

2023-07-10 06:03 UTC, DanielKBV approved these changes

2023-07-10 06:21 UTC, djarkimbaevbakyt6561 approved these changes

2023-07-10 06:45 UTC, SagynTopchuev approved these changes

2023-07-10 09:59 UTC, AziatAbd commented
исправить header. По возможности добавить hover для иконок

2023-07-10 10:00 UTC, AziatAbd requested changes

2023-07-10 10:00 UTC, AziatAbd commented on src/index.css
> +   font-family: 'Ubuntu', sans-serif;
' } ' забыли

2023-07-11 08:28 UTC, AziatAbd commented
header:
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/c7384197-8f31-42da-be01-c918dab618c4)

fix header:
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/5502b2c7-a0cf-45e3-a45e-a58ef391d68b)

2023-07-11 11:12 UTC, merged