Feature/calendar
peaksoft-school/gadgetarium-js9 pull request #20
Opened 2023-07-16 14:39 UTC by Tugolbay

2023-07-17 17:37 UTC, djarkimbaevbakyt6561 approved these changes

2023-07-18 07:27 UTC, DanielKBV approved these changes

2023-07-18 11:26 UTC, DanielKBV approved these changes

2023-07-18 12:29 UTC, SagynTopchuev approved these changes

2023-07-18 14:24 UTC, AziatAbd requested changes

2023-07-18 14:24 UTC, AziatAbd commented on src/components/calendar/Calendar.jsx
> +      <div>
не нужен

2023-07-18 14:24 UTC, AziatAbd commented on src/components/calendar/Calendar.jsx
> +export const Calendar = ({ dd, minDates = true }) => {
через пропс должны приходить value, onChange

2023-07-19 07:57 UTC, djarkimbaevbakyt6561 approved these changes

2023-07-19 08:00 UTC, Suli191 approved these changes

2023-07-21 06:25 UTC, merged