Feature/fag
peaksoft-school/gadgetarium-js9 pull request #23
Opened 2023-07-18 10:03 UTC by SagynTopchuev

2023-07-21 17:08 UTC, djarkimbaevbakyt6561 commented on src/assets/icons/map.svg
в моих icons есть эта иконка вот там его и возьми называется travel-map-location-icon и до 
этого сделай pull чтобы получить icons

2023-07-21 17:08 UTC, djarkimbaevbakyt6561 commented on src/App.jsx
> +         <Contacts />
App должен быть чистым убери Contacts

2023-07-22 10:54 UTC, djarkimbaevbakyt6561 approved these changes

2023-07-23 07:47 UTC, Tugolbay approved these changes

2023-07-24 05:39 UTC, DanielKBV commented on src/components/contacts/userInfo.jsx
> +      name: '',
do the validation normally

2023-07-31 05:35 UTC, DanielKBV commented on src/components/contacts/Map.jsx
> +   useEffect(() => {
переделай на yandex map

2023-08-02 10:37 UTC, DanielKBV approved these changes

2023-08-03 04:29 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/e99cb105-a213-410d-922a-ef2f0c28b707)
если нажму на FAQ то меня должно перекинуть туда

2023-08-03 04:30 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/cff8190c-6e58-46ed-a8e0-af6e6a6676d2)
добавь breadcrumbs

2023-08-03 04:39 UTC, AziatAbd requested changes

2023-08-03 04:39 UTC, AziatAbd commented on src/components/fag/Fag.jsx
> +export const FAG = () => {
может быть FAQ?

2023-08-03 04:39 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/95895858-4d63-4fc0-af7d-d34d3e8d1b3b)
чё за фигня

2023-08-03 04:40 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/e1d596b3-36b3-4f72-af53-acf9f94781dc)
в поле для номера можно писать текст? Круто.

2023-08-03 04:41 UTC, AziatAbd commented
Figma:

![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/10487111-02d7-4555-b2df-a37c5e11e808)

Your:

![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/b16f381f-08ac-4cac-a27d-d5e45c661e2e)

чувствуешь разницу?

2023-08-04 03:50 UTC, merged