Feature/main page
peaksoft-school/gadgetarium-js9 pull request #34
Opened 2023-08-15 16:33 UTC by djarkimbaevbakyt6561

2023-08-21 07:15 UTC, DanielKBV approved these changes

2023-08-22 05:53 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/9a0a94d2-7f29-4a73-904f-c84844719e84)
пустыми не должны быть, сделай какой-нибудь текст и убери кнопку если нету карточек

2023-08-22 05:53 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/c0c39050-8282-4596-8916-4ed10bcbd2ea)
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/7404cd56-30e0-4653-ba39-7bb305a1fd88)
сделай для них тоже запросы

2023-08-24 04:17 UTC, AziatAbd requested changes

2023-08-24 04:17 UTC, AziatAbd commented on src/components/user/main.page/MainPage.jsx
> +            <FilteredProducts array="novelties">Новинки</FilteredProducts>
здесь novelties а в других компонентах novelities, исправь

2023-08-24 04:17 UTC, AziatAbd commented on src/api/main.page.service.js
просто mainPageService

2023-08-24 04:17 UTC, AziatAbd commented on src/components/user/main.page/MainPage.jsx
> +            <FilteredProducts array="novelties">Новинки</FilteredProducts>
из-за этого не работает запрос

2023-08-24 06:25 UTC, merged