Feature/favorite
peaksoft-school/gadgetarium-js9 pull request #38
Opened 2023-08-23 03:20 UTC by djarkimbaevbakyt6561

2023-08-24 04:36 UTC, DanielKBV commented on src/store/favorite/favorite.slice.js
> +
Cannot read properties of null (reading 'length')
TypeError: Cannot read properties of null (reading 'length')

2023-08-24 11:25 UTC, Tugolbay approved these changes

2023-08-30 09:07 UTC, AziatAbd requested changes

2023-08-30 09:07 UTC, AziatAbd commented on src/components/user/favorite/FavoriteHover.jsx
> +   }
смысл открывать then catch если ты и так используешь dispatch у которого есть try catch

2023-08-30 09:07 UTC, AziatAbd commented on src/components/user/favorite/FavoriteHover.jsx
> +   }
вызывай get запрос внутри неё, а здесь

2023-08-30 09:07 UTC, AziatAbd commented on src/components/user/favorite/FavoriteHover.jsx
давайте имена файлам логические имена а не это

2023-08-30 09:07 UTC, AziatAbd commented on src/components/user/product.card/ProductCard.jsx
> +               dispatch(getFavoriteItems())
тоже самое, зачем unwrap для dispatch передай через пропс нужные данные и используй их в createAsyncThunk

2023-08-30 09:07 UTC, AziatAbd commented on src/components/user/product.card/ProductCard.jsx
> +               dispatch(getFavoriteItems())
исправь все места где использовал unwrap

2023-09-01 06:17 UTC, AziatAbd requested changes

2023-09-01 06:17 UTC, AziatAbd commented on src/components/user/AuthorizationModal.jsx
> +      }
async await нужен для асинхронной функции, а dispatch синхронная, я не понимаю почему ты здесь используешь их и еще try catch

2023-09-01 06:17 UTC, AziatAbd commented on src/components/user/AuthorizationModal.jsx
> +      }
передавай через пропсы snackbarHandler и используй их там. Так-же в createAsyncThunk есть свой dispatch, как думаешь, почему? Чтобы отправлять сигнал там а не здесь

2023-09-01 06:17 UTC, AziatAbd commented on src/components/user/product.card/ProductCard.jsx
>     const toggleComparisonHandler = () => {
удали если она не нужна

2023-09-01 06:17 UTC, AziatAbd commented on src/components/user/product.card/ProductCard.jsx
>        console.log(id)
удали все консолки

2023-09-01 06:17 UTC, AziatAbd commented on src/components/user/product.card/ProductCard.jsx
> +            .unwrap()
что из слов 'не используй unwrap' не понятны?

2023-09-01 08:31 UTC, djarkimbaevbakyt6561 commented on src/components/user/product.card/ProductCard.jsx
>        console.log(id)
его удалить Туголбай байке когда закончить свой таск

2023-09-01 13:13 UTC, djarkimbaevbakyt6561 commented on src/components/user/AuthorizationModal.jsx
> +      }
тогда проблемы с signIn будет я попробовал но не получилось

2023-09-03 09:39 UTC, merged