adding a select category
peaksoft-school/gadgetarium-js9 pull request #8
Opened 2023-07-07 21:20 UTC by djarkimbaevbakyt6561

2023-07-08 04:33 UTC, DanielKBV commented on src/App.jsx
> +            <CategorySelect componentIcon={MobileIcon}>
коментарийлерди алып app.js башында кандай болсо ошондой кылып ондо

2023-07-08 05:56 UTC, DanielKBV approved these changes

2023-07-08 10:53 UTC, SagynTopchuev approved these changes

2023-07-14 10:33 UTC, AziatAbd requested changes

2023-07-14 10:33 UTC, AziatAbd commented on .eslintrc.json
> +      "import/no-extraneous-dependencies": "import/no-extraneous-dependencies",
удали это

2023-07-14 10:33 UTC, AziatAbd commented on src/components/UI/category.select/CategorySelect.jsx
> +<StyledMenuItem key={el} onClick={handleMouseLeave}>
если я выберу какую-нибудь категорию он должен мне вернуть его id

2023-07-14 10:33 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/1bf3b947-58bf-4884-8502-98408ab0e051)
он должен появляться справа

2023-07-14 10:42 UTC, AziatAbd commented
![image](https://github.com/peaksoft-school/gadgetarium-js9/assets/115453436/31c1740e-db8d-40fe-85b2-1089e0121a6a)
открой какой-нибудь готовый массив в general

2023-07-15 12:05 UTC, merged